[package]
name = "minhttp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
dotenvy = { git = "https://github.com/allan2/dotenvy", features = ["macros"] }
futures-rustls = "0.26.0"
httparse = "1.10.1"
httpdate = "1.0.3"
rustls = "0.23.28"
rustls-pemfile = "2.2.0"
smol = "2.0.2"
